### ISSUE TITLE
Translate .svg images

### ISSUE THREAD

**Issue by mahdiHashemi14** [javascript-tutorial/fa.javascript.info#116]
I like to translate .svg files.
Is there any recommended application that I can use?
When the translation is done, should I just upload the .svg file or something else?

**Comment by mahdyar** [comment]
I don't think that'd be necessary, and Instead of that, if you could help us translate the remaining untranslated articles, it'd be much more helpful. when `fa.javascript.info` goes live, we'll have plenty of time for these minor reforms. 
Besides that, I don't see the images being translated in any other translations.

@iliakan Any thoughts?

**Comment by mahdiHashemi14** [comment]
> I don't think that'd be necessary, and Instead of that, if you could help us translate the remaining untranslated articles, it'd be much more helpful. when `fa.javascript.info` goes live, we'll have plenty of time for these minor reforms.
> Besides that, I don't see the images being translated in any other translations.
> 
> @iliakan Any thoughts?

Actually I want to translate objects chapter and in my opinion if the images could be translated in that chapter, it would help a lot with learning.

**Comment by iliakan** [comment]
To translate SVG, you need to translate `images.yml`.

Please see https://github.com/javascript-tutorial/server#translating-images

**Comment by mahdiHashemi14** [comment]
> To translate SVG, you need to translate `images.yml`.
> 
> Please see https://github.com/javascript-tutorial/server#translating-images

Thank you
